### ISSUE TITLE
Steam OAuth

### ISSUE THREAD

**Issue by Freenex1911** [FriendsOfFlarum/oauth#23]
I know there is already a Steam OAuth integration out there but I really like to have everything in one place and the FriendsOfFlarum plugins are well thought out imo.

**Comment by DavideIadeluca** [comment]
> I know there is already a Steam OAuth integration out there but I really like to have everything in one place and the FriendsOfFlarum plugins are well thought out imo.

You need to create an issue in https://github.com/NomisCZ/flarum-ext-auth-steam for that, as it's currently not planned to include Steam as a Bundled provider in `fof/oauth`.
