### ISSUE TITLE
"Only show the Log In Button icons (alternative layout)" option does not work on Google button

### ISSUE THREAD

**Issue by rafaucau** [FriendsOfFlarum/oauth#24]
## Bug Report

**Current Behavior**
The "Only show the Log In Button icons (alternative layout)" option does not work on the Google button. It looks very bad.

**Steps to Reproduce**
1. Enable "Only show the Log In Button icons (alternative layout)"
2. Enable sign in with Google

**Expected Behavior**
The Google login button should look like the rest of the buttons.

**Screenshots**
![image](https://user-images.githubusercontent.com/25438601/114775327-771a2700-9d71-11eb-87ff-d3b34d851c45.png) 
![image](https://user-images.githubusercontent.com/25438601/114775688-e0019f00-9d71-11eb-89c3-02837926c6d2.png)

**Comment by clarkwinkelmann** [comment]
That's expected behavior. That's the only design allowed by Google's branding guidelines.

https://developers.google.com/identity/branding-guidelines

We didn't want to remove the alternative layout just because you have Google enabled, but it's true that it most likely won't work well together.

**Comment by rafaucau** [comment]
@clarkwinkelmann 
If not following Google's guidelines is illegal then it can still be done better.
E.g. Google button can be moved to the end of the list, centered on a new line

**Comment by clarkwinkelmann** [comment]
Actually, it was the last item and it might have been centered. But since then we added the LinkedIn button at the end :sweat_smile: 

We could move Google back to the end indeed.
