### ISSUE TITLE
Add spacer underneath SSO buttons, button width 100%

### ISSUE THREAD

**Issue by n4n0GH** [FriendsOfFlarum/oauth#33]
## Feature Request

When activating and using at least one OAuth2 SSO method there should be a clear visual distinction between the SSO buttons and the default core login/signup as to make it easy to understand that you'd do one _or_ the other.

Also the buttons should fill out the same width as the core input fields.

**Comment by DavideIadeluca** [comment]
I think having the OAuth Providers not be the same width and with a slightly different styling is exactly providing the visual distinction you are looking for. Not sure how the design was back then but at least today I think it's fine as it is. Each Community Manager / Maintainer is encouraged to style the UI how they seem fit :)

**Comment by n4n0GH** [comment]
I mean thanks for getting back to this but lmao
