### ISSUE TITLE
Invalid email

### ISSUE THREAD

**Issue by mzch** [FriendsOfFlarum/oauth#4]
By using Discord or Twitter, I got `Invalid email` error. I couldn’t login.
Both shows authentication page and `Authorize` button, but when I clicked `Authorize`, go the error.

**Comment by clarkwinkelmann** [comment]
Are you able to share a screenshot of the error?

**Comment by mzch** [comment]
Well, Please see below:

<img width="1525" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/100534830-95fe9d80-3256-11eb-8be7-17b7c6c441a7.png">

**Comment by datitisev** [comment]
The error `invalid_email` is only thrown by the extension when the email from the provider isn't passed or it is empty.

For twitter, you need to make sure your application has the Request Email permission
> You will need to set a Terms of Service URL and a Privacy Policy URL. Make sure to then add the request email permission.

Not sure why Discord would fail like that 🤔

**Comment by mzch** [comment]
Oh, I found `Additional Permission` on the Permission tag of Twitter Developer Portal. When I checked `Request email address from users`, FoF works well. Thanks.

And sorry, about Discord, the error message isn't `invalid_email` but `{"error":"invalid_client"}`. Could you tell me how to fix this?

**Comment by datitisev** [comment]
Not sure. Your client ID might not be correct.

**Comment by mzch** [comment]
Ouch! I mistook client secret. All fixed. Thanks!
