### ISSUE TITLE
Oauth for association instead of unique account creation

### ISSUE THREAD

**Issue by AvianAeternum** [FriendsOfFlarum/oauth#41]
## Feature Request

the Ouath plugin currently does not allow an individual user to connect accounts together, logging in with any given provider creates a new account.

A clear and concise description of what the problem is. eg. I have an issue when [...]

I would instead like a different mode of the ouath plugin where the user can only create an account with one of the selected methods (oauth provider, or local username and password) and then in order to sign in with other providers, the user goes to account settings and can connect other accounts to their forum account. Once connected the user then can login with that provider if they wish on the login screen. or dont add the last part, doesnt matter. The reason for this is to allow me to sync user roles across platforms, in this case i want to grant discord roles based on forum roles or vice versa with a separate addon, but need that information to be available on the users account so i know what accounts to give roles too.

**Comment by clarkwinkelmann** [comment]
I think Flarum intends to offer an API for this at some point.

Creating this right now would equate to an almost completely new and more complex extension compared to the current implementation in FoF OAuth. So I doubt we will take on this work unless it is maybe sponsored.

If core offers the API for connected accounts in the future we might rewrite this extension to take advantage of it as the most of the work would have already been done by creating the API and UI components in core. But I don't think anyone is currently taking on this task in core.

**Comment by AvianAeternum** [comment]
Understandable, I'll probably hire someone to do it then.
