### ISSUE TITLE
telegram login

### ISSUE THREAD

**Issue by Minecon724** [FriendsOfFlarum/oauth#46]
https://core.telegram.org/widgets/login could help

**Comment by jiangyin14** [comment]
there are some plugins can do this in Extiverse nowadays, go and check it out

**Comment by DavideIadeluca** [comment]
Hi @Minecon724, thanks for your suggestion. Currently, it's not planned to add Telegram OAuth as a bundled provider in `fof/oauth`.

As @jiangyin14 mentioned, an Extension already exists https://flarum.org/extension/ghostiq/flarumtelegram, but it doesn't extend `fof/oauth` and is unlikely to work with Flarum v1.8.5. If you still need the functionality, I would suggest writing your own Extension.  You can use some of the existing providers as a reference how to implement it.
