### ISSUE TITLE
Add Support for Mastodon & Pixelfed

### ISSUE THREAD

**Issue by mitexleo** [FriendsOfFlarum/oauth#55]
Hi,
I hope you guys are well aware of the fediverse.
Would you mind adding support for login with Mastodon and Pixelfed ? 
It would be awesome for integration.
Thanks.

**Comment by DavideIadeluca** [comment]
Hi @mitexleo, thanks for your suggestion. Currently it's not planned to add Mastodon or Pixelfed as a bundled provider in `fof/oauth`. If you still need the functionality, I would suggest writing your own extension(s). You can use some of the existing providers as a reference how to implement it.
