### ISSUE TITLE
There should be separate translation strings for providers names in "Log In with {provider}" button

### ISSUE THREAD

**Issue by rob006** [FriendsOfFlarum/oauth#6]
Because the same key is used in complete different contexts, it is impossible to translate this correctly in Polish - while provider name is "Facebook", I need "Zaloguj się za pomocą Facebook**a**" in login button.

**Comment by clarkwinkelmann** [comment]
I agree this would make more sense. If there's no objection from other FoF members I'm going to make the change.

**Comment by datitisev** [comment]
Added in v1 release. From updated README:

> #### Translation
>
> You can replace the text for the forum sign in buttons in two ways.
> - Use `fof-oauth.forum.providers.<name>` to replace the name of the provider on the forum side
> - Use `fof-oauth.forum.log_in.with_<name>_button` to replace the entire button "Log In with <name>" text

**Comment by rob006** [comment]
Do you have plans to add these phrases to https://github.com/FriendsOfFlarum/oauth/blob/master/resources/locale/en.yml? Without this it will be really hard for translators to realize that they can translate this phrase individually for each provider.

**Comment by datitisev** [comment]
Hm... I'll see if I can add a comment. I don't want to add these phrases as their usage replaces the others, so it would be pointless.

**Comment by datitisev** [comment]
I added comments, hopefully they help - https://github.com/FriendsOfFlarum/oauth/commit/4d4c3472cbbf971323ff499d0b303f626c62141c.

**Comment by rob006** [comment]
Comments do not change anything for users of https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate. I think that using aliases (as `fof-oauth.forum.log_in.with_google_button: => fof-oauth.forum.log_in.with_button`) would be more straightforward and make code less magic.

**Comment by datitisev** [comment]
Ah, I see. Problem with your example is that the `with_google` button does not take a parameter (google should be in that string already) - having it take a provider parameter would be confusing.

**Comment by rob006** [comment]
@datitisev I'm not sure if I understand. The problem is that if phrases are not present in https://github.com/FriendsOfFlarum/oauth/blob/master/resources/locale/en.yml, Weblate will not detect them and translators won't be able translate them. I could solve this by some kind of stub that will be used to fetch additional phrases for this extensions, but I won't be able to reference default translation (`=> fof-oauth.forum.log_in.with_button` won't work, because provider name is not passed to default phrase) and everyone will need to translate button for every provider individually, even if universal template would work fine for their language. 

Passing provider name [here](https://github.com/FriendsOfFlarum/oauth/blob/329fcb918abbae754e7d2a4272f66e1942002205/js/src/forum/index.js#L11) would make it manageable, but in general I really don't like how this was solved here. Flarum already has convention for referencing translations, that allows translators to translate each context individually without need to duplicate the same translation multiple times if it is not needed (`=>` syntax). It is documented, well known and translators-friendly. Why reinvent the wheel and create another solution (`app.translator.trans(KEY) !== KEY`), that is tricky to understand without reading extension code, and is really inconvenient for translators?

**Comment by datitisev** [comment]
I implemented different solutions. One allow you to change the provider text alone in the forum side - this could be replaced with a reference. 

The second cannot be replaced with a reference cause its specific to the entire button text of one button, and wouldn't make sense to pass a provider name to the key specific to that provider. `with_google_button` should have `Google` translated in there, not `{provider}`.

I think your issue is solved with the former solution I mention, which is the `fof-oauth.forum.providers.<name>`, so I can add references to that.

**Comment by rob006** [comment]
> The second cannot be replaced with a reference cause its specific to the entire button text of one button, and wouldn't make sense to pass a provider name to the key specific to that provider. `with_google_button` should have `Google` translated in there, not `{provider}`.

It makes sense if default translation (in that case `with_button` used as reference) uses provider name. And even if not, there is nothing wrong with passing redundant parameters. It will be the standard approach when gender will be supported by Flarum - gender will be passed to translation even if source string does not use it.

Also I'm not sure why do you think reference cannot be used here. Something like this should work fine:

```yaml
fof-oauth:
  forum:
    log_in:
      with_button: Log In with {provider}
      with_google_button: '=> fof-oauth.forum.log_in.with_button'
      #...
    providers:
      github: '=> fof-oauth.lib.providers.google'
      #...

  lib:
    providers:
      github: GitHub
      #...
```

And the whole JS logic for translation could be simplified to:

```js
export const translateLogIn = (name) => {
    return app.translator.trans(`fof-oauth.forum.log_in.with_${name}_button`, {
        provider: app.translator.trans(`fof-oauth.forum.providers.${name}`),
    });
};
```

**Comment by datitisev** [comment]
Hm yeah I guess. I don't know, I think I was trying to keep the en.yml as simple & clean as possible while having the features in case they were necessary.

**Comment by rob006** [comment]
@datitisev Just to be clear, will you simplify translations to use references, or I need to try to solve it on my own for Weblate users?

**Comment by datitisev** [comment]
@rob006 I'll do it.

**Comment by datitisev** [comment]
Tagged `v1.0.1`, forgot to do it after that commit for some reason.
